# /home/ncacord/qRaphael/logic/text_chat_logic.py

# Description: This file contains the logic for the text chat functionality.

import json

# Load follow-up messages from the configuration file
FOLLOWUP_CONFIG_FILE = "/home/ncacord/qRaphael/config/followup_messages.json"

with open(FOLLOWUP_CONFIG_FILE, "r") as file:
    followup_config = json.load(file)

followup_messages = followup_config["keywords"]
default_message = followup_config["default_message"]

# Define the follow-up message logic
def get_followup_message(prompt, generated_text):
    """
    Determine the follow-up message based on the prompt and generated text.

    Args:
    - prompt (str): The initial prompt provided by the user.
    - generated_text (str): The text generated by the model.

    Returns:
    - str: The follow-up message.
    """
    # Check for keywords in the prompt
    prompt_lower = prompt.lower()
    for keyword, message in followup_messages.items():
        if keyword in prompt_lower:
            return message

    # Check for keywords in the generated text
    generated_text_lower = generated_text.lower()
    for keyword, message in followup_messages.items():
        if keyword in generated_text_lower:
            return message

    # Default follow-up message
    return default_message
