# /home/ncacord/qRaphael/logic/text_chat_logic.py

# Description: This file contains the logic for the text chat functionality.


# Follow-up message logic
def get_followup_message(prompt, generated_text):
    """
    Determine the follow-up message based on the prompt and generated text.

    Args:
    - prompt (str): The initial prompt provided by the user.
    - generated_text (str): The text generated by the model.

    Returns:
    - str: The follow-up message.
    """
    # Define conditions based on the prompt
    prompt_lower = prompt.lower()
    if "moon" in prompt_lower:
        return "Would you like to know more about space?"
    elif "relativity" in prompt_lower:
        return "Do you have any questions about Einstein's theory of relativity?"
    elif "newton" in prompt_lower or "law" in prompt_lower:
        return "Would you like to hear more examples of Newton's laws in action?"
    elif "bacon" in prompt_lower:
        return "Are you interested in more information about different types of bacon?"
    elif "story" in prompt_lower or "once upon a time" in prompt_lower:
        return "Would you like to hear another story or continue this one?"

    # Define conditions based on the generated text
    if "king" in generated_text.lower() or "queen" in generated_text.lower():
        return "Would you like to hear more about the royal family?"
    elif "space" in generated_text.lower() or "planet" in generated_text.lower():
        return "Would you like to learn about other celestial bodies?"
    elif "gravity" in generated_text.lower():
        return "Do you have any specific questions about gravity?"

    # Default follow-up message
    return "Will that be all, or did you need something else?"
